### ISSUE TITLE
Cannot find type 'RSIBaseShareViewController' in scope

### ISSUE THREAD

**Issue by bgeerdes** [watate/file_share_intent#4]
When I update to 3.0.3 my `ShareViewController.swift` is no longer able to find RSIBaseShareViewController.

<img width="864" height="86" alt="Image" src="https://github.com/user-attachments/assets/86cbd7ec-4dae-42e9-affe-47c461ce0e90" />

The 3.0.3 change log says that it:

> [Created] a separate sub-pod (file_share_intent_models) that contains only the Share Extension classes without any Flutter dependency.

Is there something I need to do to see the classes now that they're in file_share_intent_models? I went through the README instructions again and didn't see anything.

**Comment by JM-star** [comment]
Yes, I have also encountered this issue. The author's README has not been updated, and my intention was to replace the old ‘reced_sharing_intent‘ plugin, which has not been updated for a long time and is not compatible with the latest Xcode26 compilation requirements

**Comment by xiwangfuture-alt** [comment]
I solve it by copying  RSIBaseShareViewController.swift to my extention project.

**Comment by AbdulazizAlnahhas** [comment]
file_share_intent's podspec excludes RSIShareViewController.swift and  RSIBaseShareViewController.swift from the main pod (so it won't link Flutter into extensions). Share extension code lives in the separate file_share_intent_models pod. so you have to add that pod to the extension target 

   target 'Share_extension' do
      inherit! :search_paths
      pod 'file_share_intent_models', // <= Add this 2 line here
           :path => '.symlinks/plugins/file_share_intent/ios/Models'
    end

and switching the import. 
`import file_share_intent_models`
in ShareViewController.swift

**Comment by bgeerdes** [comment]
Thank you @AbdulazizAlnahhas; that fixed my build issues. I will create a pull request that updates the README.

@watate, one other thing I've noticed is that the project has a deployment target of iOS 12.0. But it looks like with 3.0.3, we actually went from 13.0 to 14.0. If I try to build with 13 I get:

```
Swift Compiler Error (Xcode): 'UTType' is only available in iOS 14.0 or newer
/Users/bruce/.pub-cache/hosted/pub.dev/file_share_intent-3.0.3/ios/Models/Sources/RSIBaseShareViewController.swift:151:49
```

If you're okay with it, I'll update references of 12.0 to 14.0 in the README and podspecs in my PR as well.

**Comment by bgeerdes** [comment]
I am now building but have had no success sharing a file (from Files) to my app using v3.0.3. My ShareViewController never gets invoked. Switching back to v3.0.2 works fine. I see this issue regardless of iOS 18/26 or Xcode 16/26.

I have updated the example app to use Abdul's suggestions above and to target iOS 14 (so it builds) and see the same thing: `Option A: Seamless Sharing` invokes the app but the app does not see the shared file via FileShareIntent. 

I am also not seeing any shared files when invoking the example app's default `Option B: Traditional Compose Dialog`.

@AbdulazizAlnahhas I see that you created a new issue with a problem you are having sharing screenshots. But apparently you've had success sharing from the Photos app using v3.0.3? I'm not even seeing that. Are there any other changes you made other than the ones you mentioned above?

**Comment by AbdulazizAlnahhas** [comment]
You’re right, @bgeerdes. I used RSIBaseShareViewController (silent share), and it worked properly. But when I tried RSIShareViewController, the ShareViewController was never invoked.

**Comment by bgeerdes** [comment]
@AbdulazizAlnahhas If you're using the default example "ShareViewController extending RSIShareViewController", you need to change `shouldAutoRedirect` to return true (or comment it out). Maybe that's why it's not working for you? (I ran into this.)

**Comment by ikuzmin-glitch** [comment]
@bgeerdes, @AbdulazizAlnahhas, you can set v3.0.2 and apply solution from another fork (https://github.com/KasemJaffer/receive_sharing_intent/issues/382#issuecomment-3311362688), until new fix is released. It worked for me.
